# Generated by Django 5.0.4 on 2024-04-20 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diabetes',
            name='Age',
            field=models.FloatField(max_length=20),
        ),
        migrations.AlterField(
            model_name='diabetes',
            name='BMI',
            field=models.FloatField(max_length=20),
        ),
        migrations.AlterField(
            model_name='diabetes',
            name='BloodPressure',
            field=models.FloatField(max_length=20),
        ),
        migrations.AlterField(
            model_name='diabetes',
            name='DiabetesPedigreeFucntion',
            field=models.FloatField(max_length=20),
        ),
        migrations.AlterField(
            model_name='diabetes',
            name='Glucose',
            field=models.FloatField(max_length=20),
        ),
        migrations.AlterField(
            model_name='diabetes',
            name='Insulin',
            field=models.FloatField(max_length=20),
        ),
        migrations.AlterField(
            model_name='diabetes',
            name='SkinThickness',
            field=models.FloatField(max_length=20),
        ),
        migrations.AlterField(
            model_name='diabetes',
            name='pregnancies',
            field=models.FloatField(max_length=20),
        ),
    ]
