# Generated by Django 5.0.4 on 2024-04-20 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_diabetes_age_alter_diabetes_bmi_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diabetes',
            old_name='DiabetesPedigreeFucntion',
            new_name='DiabetesPedigreeFunction',
        ),
        migrations.RenameField(
            model_name='diabetes',
            old_name='pregnancies',
            new_name='Pregnancies',
        ),
    ]
